spring.application.name=e-commerce-website

#Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/e-commerce
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#JPA/Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver

#Signing key
jwt.signing.key=${JWT_SIGNING_KEY}
jwt.expiration = 86400000

#Upload Image
app.upload.dir = ./uploads

#Frontend URL
app.frontend-url=http://127.0.0.1:5500

#Spring Mail Sender Config
spring.mail.host = smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#Google OAuth
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

#Facebook Oauth
spring.security.oauth2.client.registration.facebook.client-id=${FACEBOOK_CLIENT_ID}
spring.security.oauth2.client.registration.facebook.client-secret=${FACEBOOK_CLIENT_SECRET}
spring.security.oauth2.client.registration.facebook.scope=email,profile_profile

#Password Rest Token
app.password.reset.expiration = 300000