spring.application.name=e-commerce-website

#Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/e-commerce
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#JPA/Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver

#Signing key
jwt.signing.key=${JWT_SIGNING_KEY}
jwt.expiration = 86400000

#Upload Image
app.upload.dir = ./uploads
